// AUTO-GENERATED by scripts/gen-mock-data.js — do not hand-edit.
// Static catalog data for the frontend-only demo build (no database).
// Regenerate with: node scripts/gen-mock-data.js

import type { CategoryRecord, ProductRecord } from './mockTypes';

export const MOCK_CATEGORIES: CategoryRecord[] = [
  {
    "id": "cat-0001",
    "name": "Electronics",
    "slug": "electronics",
    "description": "Phones, laptops, audio, and everyday tech.",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Man_with_smartphone_and_laptop_%28Unsplash%29.jpg/960px-Man_with_smartphone_and_laptop_%28Unsplash%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sortOrder": 0,
    "productCount": 6
  },
  {
    "id": "cat-0042",
    "name": "Fashion",
    "slug": "fashion",
    "description": "Men's and women's apparel, footwear, and accessories.",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Toni_Frissell%2C_Fashion_model%2C_Washington%2C_D.C.%2C_1949.jpg/960px-Toni_Frissell%2C_Fashion_model%2C_Washington%2C_D.C.%2C_1949.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sortOrder": 1,
    "productCount": 6
  },
  {
    "id": "cat-0092",
    "name": "Home & Kitchen",
    "slug": "home-and-kitchen",
    "description": "Furniture, cookware, and everyday home essentials.",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Olive_cookware_in_Montenegro.jpg/960px-Olive_cookware_in_Montenegro.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sortOrder": 2,
    "productCount": 6
  },
  {
    "id": "cat-0126",
    "name": "Beauty & Personal Care",
    "slug": "beauty-and-personal-care",
    "description": "Skincare, haircare, and grooming products.",
    "imageUrl": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Lipstick_in_application_%286065375905%29.jpg/960px-Lipstick_in_application_%286065375905%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sortOrder": 3,
    "productCount": 4
  },
  {
    "id": "cat-0149",
    "name": "Sports & Outdoors",
    "slug": "sports-and-outdoors",
    "description": "Fitness gear, outdoor equipment, and activewear.",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Oakley_yoga_mat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "sortOrder": 4,
    "productCount": 4
  }
];

export const MOCK_PRODUCTS: ProductRecord[] = [
  {
    "id": "prod-0006",
    "name": "Aurora Wireless Headphones",
    "slug": "aurora-wireless-headphones",
    "sku": "SKU-1001",
    "description": "Aurora Wireless Headphones from Aurora. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Electronics collection.",
    "shortDescription": "Aurora · Electronics",
    "price": 89.99,
    "compareAtPrice": 109.99,
    "stock": 27,
    "brand": "Aurora",
    "isFeatured": true,
    "avgRating": 4.2,
    "reviewCount": 114,
    "categoryId": "cat-0001",
    "categorySlug": "electronics",
    "categoryName": "Electronics",
    "images": [
      {
        "id": "img-0007",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Loud_environment_headphones.jpg/960px-Loud_environment_headphones.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Aurora Wireless Headphones — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0008",
        "url": "https://upload.wikimedia.org/wikipedia/commons/4/41/GradoPrestige-HeadphoneArticle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "Aurora Wireless Headphones — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0009",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Homemade_high_level_headphones_with_portable_radio_01.jpg/960px-Homemade_high_level_headphones_with_portable_radio_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Aurora Wireless Headphones — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0010",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Homemade_high_level_headphones_with_portable_radio_02.jpg/960px-Homemade_high_level_headphones_with_portable_radio_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Aurora Wireless Headphones — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0002",
        "sku": "SKU-1001-V1",
        "name": "Aurora Wireless Headphones — Black",
        "attributes": {
          "color": "Black"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0003",
        "sku": "SKU-1001-V2",
        "name": "Aurora Wireless Headphones — White",
        "attributes": {
          "color": "White"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0004",
        "sku": "SKU-1001-V3",
        "name": "Aurora Wireless Headphones — Blue",
        "attributes": {
          "color": "Blue"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0005",
        "sku": "SKU-1001-V4",
        "name": "Aurora Wireless Headphones — Red",
        "attributes": {
          "color": "Red"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-14T10:44:40.288Z"
  },
  {
    "id": "prod-0015",
    "name": "Pulse Smartwatch Series 4",
    "slug": "pulse-smartwatch-series-4",
    "sku": "SKU-1002",
    "description": "Pulse Smartwatch Series 4 from Pulse. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Electronics collection.",
    "shortDescription": "Pulse · Electronics",
    "price": 149,
    "compareAtPrice": null,
    "stock": 78,
    "brand": "Pulse",
    "isFeatured": true,
    "avgRating": 3.7,
    "reviewCount": 27,
    "categoryId": "cat-0001",
    "categorySlug": "electronics",
    "categoryName": "Electronics",
    "images": [
      {
        "id": "img-0016",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/Pebble_smartwatch_size.jpg/960px-Pebble_smartwatch_size.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Pulse Smartwatch Series 4 — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0017",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Smartwatch-828786.jpg/960px-Smartwatch-828786.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Pulse Smartwatch Series 4 — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0018",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ef/Alcatel_OneTouch_Watch_Smartwatch_%2816862283991%29.jpg/960px-Alcatel_OneTouch_Watch_Smartwatch_%2816862283991%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Pulse Smartwatch Series 4 — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0019",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Yuntab_Smartwatch_%282018%29_02.jpg/960px-Yuntab_Smartwatch_%282018%29_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Pulse Smartwatch Series 4 — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0011",
        "sku": "SKU-1002-V1",
        "name": "Pulse Smartwatch Series 4 — Black",
        "attributes": {
          "color": "Black"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0012",
        "sku": "SKU-1002-V2",
        "name": "Pulse Smartwatch Series 4 — White",
        "attributes": {
          "color": "White"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0013",
        "sku": "SKU-1002-V3",
        "name": "Pulse Smartwatch Series 4 — Blue",
        "attributes": {
          "color": "Blue"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0014",
        "sku": "SKU-1002-V4",
        "name": "Pulse Smartwatch Series 4 — Red",
        "attributes": {
          "color": "Red"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-14T09:44:40.289Z"
  },
  {
    "id": "prod-0020",
    "name": "NovaBook 14\" Ultralight Laptop",
    "slug": "novabook-14-ultralight-laptop",
    "sku": "SKU-1003",
    "description": "NovaBook 14\" Ultralight Laptop from Nova. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Electronics collection.",
    "shortDescription": "Nova · Electronics",
    "price": 899,
    "compareAtPrice": 999,
    "stock": 72,
    "brand": "Nova",
    "isFeatured": false,
    "avgRating": 4.2,
    "reviewCount": 19,
    "categoryId": "cat-0001",
    "categorySlug": "electronics",
    "categoryName": "Electronics",
    "images": [
      {
        "id": "img-0021",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Man_with_smartphone_and_laptop_%28Unsplash%29.jpg/960px-Man_with_smartphone_and_laptop_%28Unsplash%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "NovaBook 14\" Ultralight Laptop — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0022",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Image_with_nested_realities_of_a_laptop_showing_the_image_of_the_same_laptop_showing_a_Wikimedia_Commons_image_of_the_laptop.jpeg/960px-Image_with_nested_realities_of_a_laptop_showing_the_image_of_the_same_laptop_showing_a_Wikimedia_Commons_image_of_the_laptop.jpeg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "NovaBook 14\" Ultralight Laptop — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0023",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/Hacker_typing_on_a_Linux_laptop_full_of_stickers.jpg/960px-Hacker_typing_on_a_Linux_laptop_full_of_stickers.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "NovaBook 14\" Ultralight Laptop — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0024",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Teen_Hands_on_Laptop_-_960x1440.jpg/960px-Teen_Hands_on_Laptop_-_960x1440.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "NovaBook 14\" Ultralight Laptop — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [],
    "createdAt": "2026-09-14T08:44:40.289Z"
  },
  {
    "id": "prod-0029",
    "name": "EchoDot Bluetooth Speaker",
    "slug": "echodot-bluetooth-speaker",
    "sku": "SKU-1004",
    "description": "EchoDot Bluetooth Speaker from Echo. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Electronics collection.",
    "shortDescription": "Echo · Electronics",
    "price": 39.5,
    "compareAtPrice": null,
    "stock": 60,
    "brand": "Echo",
    "isFeatured": false,
    "avgRating": 4.5,
    "reviewCount": 42,
    "categoryId": "cat-0001",
    "categorySlug": "electronics",
    "categoryName": "Electronics",
    "images": [
      {
        "id": "img-0030",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/JBL_Flip_3_bluetooth_speaker_%28DSCF2653%29.jpg/960px-JBL_Flip_3_bluetooth_speaker_%28DSCF2653%29.jpg",
        "altText": "EchoDot Bluetooth Speaker — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0031",
        "url": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Magnavox_horn_loudspeaker.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "EchoDot Bluetooth Speaker — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0032",
        "url": "https://upload.wikimedia.org/wikipedia/commons/2/2d/Early_home_radio_loudspeaker.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "EchoDot Bluetooth Speaker — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0033",
        "url": "https://upload.wikimedia.org/wikipedia/commons/4/48/Racon_theater_horn_loudspeaker.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "EchoDot Bluetooth Speaker — image 4",
        "sortOrder": 3
      },
      {
        "id": "img-0034",
        "url": "https://upload.wikimedia.org/wikipedia/commons/2/29/Altec_604_Duplex_Loudspeaker.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "EchoDot Bluetooth Speaker — image 5",
        "sortOrder": 4
      }
    ],
    "variants": [
      {
        "id": "var-0025",
        "sku": "SKU-1004-V1",
        "name": "EchoDot Bluetooth Speaker — Black",
        "attributes": {
          "color": "Black"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0026",
        "sku": "SKU-1004-V2",
        "name": "EchoDot Bluetooth Speaker — White",
        "attributes": {
          "color": "White"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0027",
        "sku": "SKU-1004-V3",
        "name": "EchoDot Bluetooth Speaker — Blue",
        "attributes": {
          "color": "Blue"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0028",
        "sku": "SKU-1004-V4",
        "name": "EchoDot Bluetooth Speaker — Red",
        "attributes": {
          "color": "Red"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-14T07:44:40.289Z"
  },
  {
    "id": "prod-0035",
    "name": "FastCharge 65W USB-C Adapter",
    "slug": "fastcharge-65w-usb-c-adapter",
    "sku": "SKU-1005",
    "description": "FastCharge 65W USB-C Adapter from FastCharge. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Electronics collection.",
    "shortDescription": "FastCharge · Electronics",
    "price": 24.99,
    "compareAtPrice": 29.99,
    "stock": 30,
    "brand": "FastCharge",
    "isFeatured": false,
    "avgRating": 4.4,
    "reviewCount": 114,
    "categoryId": "cat-0001",
    "categorySlug": "electronics",
    "categoryName": "Electronics",
    "images": [
      {
        "id": "img-0036",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/USB_Type-C_Cable_-_iPad_USB-C_Charger_%2845640822114%29.jpg/960px-USB_Type-C_Cable_-_iPad_USB-C_Charger_%2845640822114%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "FastCharge 65W USB-C Adapter — image 1",
        "sortOrder": 0
      }
    ],
    "variants": [],
    "createdAt": "2026-09-14T06:44:40.289Z"
  },
  {
    "id": "prod-0037",
    "name": "ClearView 27\" 4K Monitor",
    "slug": "clearview-27-4k-monitor",
    "sku": "SKU-1006",
    "description": "ClearView 27\" 4K Monitor from ClearView. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Electronics collection.",
    "shortDescription": "ClearView · Electronics",
    "price": 329,
    "compareAtPrice": null,
    "stock": 68,
    "brand": "ClearView",
    "isFeatured": false,
    "avgRating": 4.7,
    "reviewCount": 11,
    "categoryId": "cat-0001",
    "categorySlug": "electronics",
    "categoryName": "Electronics",
    "images": [
      {
        "id": "img-0038",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Computer_monitor_samsung.jpg/960px-Computer_monitor_samsung.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "ClearView 27\" 4K Monitor — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0039",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/EIZO_Foris_FG2421_VGA_computer_monitor_displaying_test_pattern.png/960px-EIZO_Foris_FG2421_VGA_computer_monitor_displaying_test_pattern.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "ClearView 27\" 4K Monitor — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0040",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Computer_monitor_remix_transparent.png/960px-Computer_monitor_remix_transparent.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "ClearView 27\" 4K Monitor — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0041",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Dell_Computer_Monitor.png/960px-Dell_Computer_Monitor.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "ClearView 27\" 4K Monitor — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [],
    "createdAt": "2026-09-14T05:44:40.289Z"
  },
  {
    "id": "prod-0047",
    "name": "Classic Cotton Crewneck Tee",
    "slug": "classic-cotton-crewneck-tee",
    "sku": "SKU-1007",
    "description": "Classic Cotton Crewneck Tee from Urban Basics. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Fashion collection.",
    "shortDescription": "Urban Basics · Fashion",
    "price": 19.99,
    "compareAtPrice": 24.99,
    "stock": 57,
    "brand": "Urban Basics",
    "isFeatured": true,
    "avgRating": 3.8,
    "reviewCount": 17,
    "categoryId": "cat-0042",
    "categorySlug": "fashion",
    "categoryName": "Fashion",
    "images": [
      {
        "id": "img-0048",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Man_in_t-shirt_posing_%28Unsplash%29.jpg/960px-Man_in_t-shirt_posing_%28Unsplash%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Classic Cotton Crewneck Tee — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0049",
        "url": "https://upload.wikimedia.org/wikipedia/commons/f/fa/Woman_in_red_t-shirt_smiling_and_looking_down.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "Classic Cotton Crewneck Tee — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0050",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/T-shirt_macro_view_%28143610293%29.jpg/960px-T-shirt_macro_view_%28143610293%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Classic Cotton Crewneck Tee — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0051",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Marcia_Fudge_with_Stay_Woke_Vote_t-shirt_in_2018.jpg/960px-Marcia_Fudge_with_Stay_Woke_Vote_t-shirt_in_2018.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Classic Cotton Crewneck Tee — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0043",
        "sku": "SKU-1007-V1",
        "name": "Classic Cotton Crewneck Tee — S",
        "attributes": {
          "size": "S"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0044",
        "sku": "SKU-1007-V2",
        "name": "Classic Cotton Crewneck Tee — M",
        "attributes": {
          "size": "M"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0045",
        "sku": "SKU-1007-V3",
        "name": "Classic Cotton Crewneck Tee — L",
        "attributes": {
          "size": "L"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0046",
        "sku": "SKU-1007-V4",
        "name": "Classic Cotton Crewneck Tee — XL",
        "attributes": {
          "size": "XL"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-14T04:44:40.289Z"
  },
  {
    "id": "prod-0056",
    "name": "Slim Fit Denim Jacket",
    "slug": "slim-fit-denim-jacket",
    "sku": "SKU-1008",
    "description": "Slim Fit Denim Jacket from Urban Basics. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Fashion collection.",
    "shortDescription": "Urban Basics · Fashion",
    "price": 64,
    "compareAtPrice": null,
    "stock": 79,
    "brand": "Urban Basics",
    "isFeatured": true,
    "avgRating": 4.2,
    "reviewCount": 9,
    "categoryId": "cat-0042",
    "categorySlug": "fashion",
    "categoryName": "Fashion",
    "images": [
      {
        "id": "img-0057",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Denim_jacket_cuff_closeup.jpg/960px-Denim_jacket_cuff_closeup.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Slim Fit Denim Jacket — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0058",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/51/Worn_Tender_Co._denim_jacket.jpg/960px-Worn_Tender_Co._denim_jacket.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Slim Fit Denim Jacket — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0059",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Man_Wearing_Black_Bads_Crew-neck_Shirt_Under_Blue_Denim_Jacket.jpg/960px-Man_Wearing_Black_Bads_Crew-neck_Shirt_Under_Blue_Denim_Jacket.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Slim Fit Denim Jacket — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0060",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/12/Denim_Jacket_Pocket_-_Macro_%2849851869231%29.jpg/960px-Denim_Jacket_Pocket_-_Macro_%2849851869231%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Slim Fit Denim Jacket — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0052",
        "sku": "SKU-1008-V1",
        "name": "Slim Fit Denim Jacket — S",
        "attributes": {
          "size": "S"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0053",
        "sku": "SKU-1008-V2",
        "name": "Slim Fit Denim Jacket — M",
        "attributes": {
          "size": "M"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0054",
        "sku": "SKU-1008-V3",
        "name": "Slim Fit Denim Jacket — L",
        "attributes": {
          "size": "L"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0055",
        "sku": "SKU-1008-V4",
        "name": "Slim Fit Denim Jacket — XL",
        "attributes": {
          "size": "XL"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-14T03:44:40.289Z"
  },
  {
    "id": "prod-0065",
    "name": "Everyday Running Sneakers",
    "slug": "everyday-running-sneakers",
    "sku": "SKU-1009",
    "description": "Everyday Running Sneakers from Stride. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Fashion collection.",
    "shortDescription": "Stride · Fashion",
    "price": 74.5,
    "compareAtPrice": 89,
    "stock": 49,
    "brand": "Stride",
    "isFeatured": false,
    "avgRating": 4.9,
    "reviewCount": 20,
    "categoryId": "cat-0042",
    "categorySlug": "fashion",
    "categoryName": "Fashion",
    "images": [
      {
        "id": "img-0066",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/North_Star_sneakers_%281%29.jpg/960px-North_Star_sneakers_%281%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Everyday Running Sneakers — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0067",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ef/North_Star_sneakers_%282%29.jpg/960px-North_Star_sneakers_%282%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Everyday Running Sneakers — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0068",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/Sneakers_.jpg/960px-Sneakers_.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Everyday Running Sneakers — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0069",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/KidsInSneakers.jpg/960px-KidsInSneakers.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Everyday Running Sneakers — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0061",
        "sku": "SKU-1009-V1",
        "name": "Everyday Running Sneakers — S",
        "attributes": {
          "size": "S"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0062",
        "sku": "SKU-1009-V2",
        "name": "Everyday Running Sneakers — M",
        "attributes": {
          "size": "M"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0063",
        "sku": "SKU-1009-V3",
        "name": "Everyday Running Sneakers — L",
        "attributes": {
          "size": "L"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0064",
        "sku": "SKU-1009-V4",
        "name": "Everyday Running Sneakers — XL",
        "attributes": {
          "size": "XL"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-14T02:44:40.289Z"
  },
  {
    "id": "prod-0070",
    "name": "Leather Minimalist Wallet",
    "slug": "leather-minimalist-wallet",
    "sku": "SKU-1010",
    "description": "Leather Minimalist Wallet from Craft & Co.. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Fashion collection.",
    "shortDescription": "Craft & Co. · Fashion",
    "price": 34,
    "compareAtPrice": null,
    "stock": 77,
    "brand": "Craft & Co.",
    "isFeatured": false,
    "avgRating": 4.6,
    "reviewCount": 53,
    "categoryId": "cat-0042",
    "categorySlug": "fashion",
    "categoryName": "Fashion",
    "images": [
      {
        "id": "img-0071",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Aarong_leather_wallet.jpg/960px-Aarong_leather_wallet.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Leather Minimalist Wallet — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0072",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Red_Leather_Wallet_Belonging_to_Elizabeth_Jared_Simmons_Lee_Upton_-_DPLA_-_1510904723f19888e4091dadaafa968a_%28page_12%29.jpg/960px-Red_Leather_Wallet_Belonging_to_Elizabeth_Jared_Simmons_Lee_Upton_-_DPLA_-_1510904723f19888e4091dadaafa968a_%28page_12%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Leather Minimalist Wallet — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0073",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/04/Leather_Wallet_with_Brass_Decoration_-_DPLA_-_5481ceb17900f03325e14ee1f22a517d_%28page_7%29.jpg/960px-Leather_Wallet_with_Brass_Decoration_-_DPLA_-_5481ceb17900f03325e14ee1f22a517d_%28page_7%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Leather Minimalist Wallet — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0074",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Leather_Wallet_Which_Belonged_to_William_Uhri_Jr._-_DPLA_-_69410fcf5b4986b7863de32973690182_%28page_5%29.jpg/960px-Leather_Wallet_Which_Belonged_to_William_Uhri_Jr._-_DPLA_-_69410fcf5b4986b7863de32973690182_%28page_5%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Leather Minimalist Wallet — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [],
    "createdAt": "2026-09-14T01:44:40.289Z"
  },
  {
    "id": "prod-0079",
    "name": "Lightweight Rain Jacket",
    "slug": "lightweight-rain-jacket",
    "sku": "SKU-1011",
    "description": "Lightweight Rain Jacket from Trailhead. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Fashion collection.",
    "shortDescription": "Trailhead · Fashion",
    "price": 58,
    "compareAtPrice": 72,
    "stock": 42,
    "brand": "Trailhead",
    "isFeatured": false,
    "avgRating": 3.9,
    "reviewCount": 87,
    "categoryId": "cat-0042",
    "categorySlug": "fashion",
    "categoryName": "Fashion",
    "images": [
      {
        "id": "img-0080",
        "url": "https://upload.wikimedia.org/wikipedia/commons/7/71/Lighted_Rain_Jacket_Worn_In_Cornwell_Park_In_Bellingham_Washington.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "Lightweight Rain Jacket — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0081",
        "url": "https://upload.wikimedia.org/wikipedia/commons/e/eb/-dailyarsenal_Pelikan_600_-fountainpen%2C_Waterman_Expert_ballpoint%2C_a_rain_jacket%2C_my_cool_hat._%285528724807%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "Lightweight Rain Jacket — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0082",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Early_Gore-Tex_hooded_rain_jacket.jpg/960px-Early_Gore-Tex_hooded_rain_jacket.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Lightweight Rain Jacket — image 3",
        "sortOrder": 2
      }
    ],
    "variants": [
      {
        "id": "var-0075",
        "sku": "SKU-1011-V1",
        "name": "Lightweight Rain Jacket — S",
        "attributes": {
          "size": "S"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0076",
        "sku": "SKU-1011-V2",
        "name": "Lightweight Rain Jacket — M",
        "attributes": {
          "size": "M"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0077",
        "sku": "SKU-1011-V3",
        "name": "Lightweight Rain Jacket — L",
        "attributes": {
          "size": "L"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0078",
        "sku": "SKU-1011-V4",
        "name": "Lightweight Rain Jacket — XL",
        "attributes": {
          "size": "XL"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-14T00:44:40.289Z"
  },
  {
    "id": "prod-0087",
    "name": "Wool Blend Scarf",
    "slug": "wool-blend-scarf",
    "sku": "SKU-1012",
    "description": "Wool Blend Scarf from Craft & Co.. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Fashion collection.",
    "shortDescription": "Craft & Co. · Fashion",
    "price": 22.5,
    "compareAtPrice": null,
    "stock": 35,
    "brand": "Craft & Co.",
    "isFeatured": false,
    "avgRating": 3.9,
    "reviewCount": 5,
    "categoryId": "cat-0042",
    "categorySlug": "fashion",
    "categoryName": "Fashion",
    "images": [
      {
        "id": "img-0088",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/35/Scarf_MET_183874.jpg/960px-Scarf_MET_183874.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Wool Blend Scarf — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0089",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/Scarf_MET_134945.jpg/960px-Scarf_MET_134945.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Wool Blend Scarf — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0090",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Scarf_MET_DP17836.jpg/960px-Scarf_MET_DP17836.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Wool Blend Scarf — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0091",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Scarf_MET_130029.jpg/960px-Scarf_MET_130029.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Wool Blend Scarf — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0083",
        "sku": "SKU-1012-V1",
        "name": "Wool Blend Scarf — Black",
        "attributes": {
          "color": "Black"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0084",
        "sku": "SKU-1012-V2",
        "name": "Wool Blend Scarf — White",
        "attributes": {
          "color": "White"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0085",
        "sku": "SKU-1012-V3",
        "name": "Wool Blend Scarf — Blue",
        "attributes": {
          "color": "Blue"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0086",
        "sku": "SKU-1012-V4",
        "name": "Wool Blend Scarf — Red",
        "attributes": {
          "color": "Red"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-13T23:44:40.289Z"
  },
  {
    "id": "prod-0093",
    "name": "Stainless Steel Cookware Set (10-Piece)",
    "slug": "stainless-steel-cookware-set-10-piece",
    "sku": "SKU-1013",
    "description": "Stainless Steel Cookware Set (10-Piece) from HearthPro. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Home & Kitchen collection.",
    "shortDescription": "HearthPro · Home & Kitchen",
    "price": 129,
    "compareAtPrice": 159,
    "stock": 82,
    "brand": "HearthPro",
    "isFeatured": true,
    "avgRating": 4.2,
    "reviewCount": 97,
    "categoryId": "cat-0092",
    "categorySlug": "home-and-kitchen",
    "categoryName": "Home & Kitchen",
    "images": [
      {
        "id": "img-0094",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Olive_cookware_in_Montenegro.jpg/960px-Olive_cookware_in_Montenegro.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Stainless Steel Cookware Set (10-Piece) — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0095",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Cookware_in_Kenya.jpg/960px-Cookware_in_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Stainless Steel Cookware Set (10-Piece) — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0096",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Cookware_outdoor%2C_Kenya.jpg/960px-Cookware_outdoor%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Stainless Steel Cookware Set (10-Piece) — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0097",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/41/Cookware_Peddler_MET_DP818786.jpg/960px-Cookware_Peddler_MET_DP818786.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Stainless Steel Cookware Set (10-Piece) — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T22:44:40.289Z"
  },
  {
    "id": "prod-0098",
    "name": "Ceramic Non-Stick Frying Pan",
    "slug": "ceramic-non-stick-frying-pan",
    "sku": "SKU-1014",
    "description": "Ceramic Non-Stick Frying Pan from HearthPro. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Home & Kitchen collection.",
    "shortDescription": "HearthPro · Home & Kitchen",
    "price": 27.99,
    "compareAtPrice": null,
    "stock": 60,
    "brand": "HearthPro",
    "isFeatured": true,
    "avgRating": 3.5,
    "reviewCount": 54,
    "categoryId": "cat-0092",
    "categorySlug": "home-and-kitchen",
    "categoryName": "Home & Kitchen",
    "images": [
      {
        "id": "img-0099",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Stove_and_earthware_cooking_pan.jpg/960px-Stove_and_earthware_cooking_pan.jpg",
        "altText": "Ceramic Non-Stick Frying Pan — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0100",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Breakfast_Skillet_%28Vg_version%29_for_two%2C_T_%40_The_Dials%2C_Brighton.jpg/960px-Breakfast_Skillet_%28Vg_version%29_for_two%2C_T_%40_The_Dials%2C_Brighton.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Ceramic Non-Stick Frying Pan — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0101",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Impossible_Skillet_with_Just_Egg.jpg/960px-Impossible_Skillet_with_Just_Egg.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Ceramic Non-Stick Frying Pan — image 3",
        "sortOrder": 2
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T21:44:40.289Z"
  },
  {
    "id": "prod-0106",
    "name": "Linen Throw Pillow Cover Set",
    "slug": "linen-throw-pillow-cover-set",
    "sku": "SKU-1015",
    "description": "Linen Throw Pillow Cover Set from Nestwell. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Home & Kitchen collection.",
    "shortDescription": "Nestwell · Home & Kitchen",
    "price": 18,
    "compareAtPrice": 22,
    "stock": 84,
    "brand": "Nestwell",
    "isFeatured": false,
    "avgRating": 4.1,
    "reviewCount": 63,
    "categoryId": "cat-0092",
    "categorySlug": "home-and-kitchen",
    "categoryName": "Home & Kitchen",
    "images": [
      {
        "id": "img-0107",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3d/Cushion_cover_MET_DP151905.jpg/960px-Cushion_cover_MET_DP151905.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Linen Throw Pillow Cover Set — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0108",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Cushion_cover_MET_DP151938.jpg/960px-Cushion_cover_MET_DP151938.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Linen Throw Pillow Cover Set — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0109",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/Cushion_cover_MET_AZ3B.jpg/960px-Cushion_cover_MET_AZ3B.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Linen Throw Pillow Cover Set — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0110",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b7/Cushion_cover_MET_175835.jpg/960px-Cushion_cover_MET_175835.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Linen Throw Pillow Cover Set — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0102",
        "sku": "SKU-1015-V1",
        "name": "Linen Throw Pillow Cover Set — Black",
        "attributes": {
          "color": "Black"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0103",
        "sku": "SKU-1015-V2",
        "name": "Linen Throw Pillow Cover Set — White",
        "attributes": {
          "color": "White"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0104",
        "sku": "SKU-1015-V3",
        "name": "Linen Throw Pillow Cover Set — Blue",
        "attributes": {
          "color": "Blue"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0105",
        "sku": "SKU-1015-V4",
        "name": "Linen Throw Pillow Cover Set — Red",
        "attributes": {
          "color": "Red"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-13T20:44:40.289Z"
  },
  {
    "id": "prod-0111",
    "name": "Electric Pour-Over Kettle",
    "slug": "electric-pour-over-kettle",
    "sku": "SKU-1016",
    "description": "Electric Pour-Over Kettle from Brewmate. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Home & Kitchen collection.",
    "shortDescription": "Brewmate · Home & Kitchen",
    "price": 44.5,
    "compareAtPrice": null,
    "stock": 46,
    "brand": "Brewmate",
    "isFeatured": false,
    "avgRating": 4.1,
    "reviewCount": 100,
    "categoryId": "cat-0092",
    "categorySlug": "home-and-kitchen",
    "categoryName": "Home & Kitchen",
    "images": [
      {
        "id": "img-0112",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Kettle_MET_DP353092.jpg/960px-Kettle_MET_DP353092.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Electric Pour-Over Kettle — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0113",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Kettle_MET_DP365635.jpg/960px-Kettle_MET_DP365635.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Electric Pour-Over Kettle — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0114",
        "url": "https://upload.wikimedia.org/wikipedia/commons/3/36/Kettle_MET_35.64.1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "Electric Pour-Over Kettle — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0115",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Soap_Kettle_%2820107646%29.jpg/960px-Soap_Kettle_%2820107646%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Electric Pour-Over Kettle — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T19:44:40.289Z"
  },
  {
    "id": "prod-0116",
    "name": "Solid Oak Coffee Table",
    "slug": "solid-oak-coffee-table",
    "sku": "SKU-1017",
    "description": "Solid Oak Coffee Table from Nestwell. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Home & Kitchen collection.",
    "shortDescription": "Nestwell · Home & Kitchen",
    "price": 219,
    "compareAtPrice": 259,
    "stock": 45,
    "brand": "Nestwell",
    "isFeatured": false,
    "avgRating": 3.9,
    "reviewCount": 7,
    "categoryId": "cat-0092",
    "categorySlug": "home-and-kitchen",
    "categoryName": "Home & Kitchen",
    "images": [
      {
        "id": "img-0117",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/Shabby_chic_coffee_table.jpg/960px-Shabby_chic_coffee_table.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Solid Oak Coffee Table — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0118",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/Noguchi_Coffee_Table_%282599969608%29.jpg/960px-Noguchi_Coffee_Table_%282599969608%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Solid Oak Coffee Table — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0119",
        "url": "https://upload.wikimedia.org/wikipedia/commons/9/93/New_coffee_table_%281%29_%2890346490%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "Solid Oak Coffee Table — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0120",
        "url": "https://upload.wikimedia.org/wikipedia/commons/8/8e/New_coffee_table_%282%29_%2890346465%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "Solid Oak Coffee Table — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T18:44:40.289Z"
  },
  {
    "id": "prod-0121",
    "name": "6-Piece Glass Storage Container Set",
    "slug": "6-piece-glass-storage-container-set",
    "sku": "SKU-1018",
    "description": "6-Piece Glass Storage Container Set from Nestwell. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Home & Kitchen collection.",
    "shortDescription": "Nestwell · Home & Kitchen",
    "price": 32.99,
    "compareAtPrice": null,
    "stock": 44,
    "brand": "Nestwell",
    "isFeatured": false,
    "avgRating": 3.6,
    "reviewCount": 51,
    "categoryId": "cat-0092",
    "categorySlug": "home-and-kitchen",
    "categoryName": "Home & Kitchen",
    "images": [
      {
        "id": "img-0122",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Lunch_box_in_KTX2.JPG/960px-Lunch_box_in_KTX2.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "6-Piece Glass Storage Container Set — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0123",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Oyster_rice_lunch_box.jpg/960px-Oyster_rice_lunch_box.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "6-Piece Glass Storage Container Set — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0124",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Youlinji_with_leek_lunch_box_of_Origin_Bento.jpg/960px-Youlinji_with_leek_lunch_box_of_Origin_Bento.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "6-Piece Glass Storage Container Set — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0125",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Skip%27s_Lunch_Box%2C_Jackson_Avenue%2C_Central_City_New_Orleans%2C_15_May_2026_-_01.jpg/960px-Skip%27s_Lunch_Box%2C_Jackson_Avenue%2C_Central_City_New_Orleans%2C_15_May_2026_-_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "6-Piece Glass Storage Container Set — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T17:44:40.289Z"
  },
  {
    "id": "prod-0127",
    "name": "Hydrating Vitamin C Serum",
    "slug": "hydrating-vitamin-c-serum",
    "sku": "SKU-1019",
    "description": "Hydrating Vitamin C Serum from Glowlab. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Beauty & Personal Care collection.",
    "shortDescription": "Glowlab · Beauty & Personal Care",
    "price": 26,
    "compareAtPrice": 32,
    "stock": 65,
    "brand": "Glowlab",
    "isFeatured": true,
    "avgRating": 4,
    "reviewCount": 28,
    "categoryId": "cat-0126",
    "categorySlug": "beauty-and-personal-care",
    "categoryName": "Beauty & Personal Care",
    "images": [
      {
        "id": "img-0128",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/86/Person_holding_an_open_jar_of_natural_skincare_product_in_a_cozy_setting_during_daylight.jpg/960px-Person_holding_an_open_jar_of_natural_skincare_product_in_a_cozy_setting_during_daylight.jpg",
        "altText": "Hydrating Vitamin C Serum — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0129",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e9/Binding_of_anti-cancer_drug_gemcitabine-squalene_to_human_serum_albumin.png/960px-Binding_of_anti-cancer_drug_gemcitabine-squalene_to_human_serum_albumin.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Hydrating Vitamin C Serum — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0130",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/The_Prime_Minister%2C_Shri_Narendra_Modi_visits_the_Serum_Institute_of_India%2C_in_Pune_on_November_28%2C_2020_%284%29.jpg/960px-The_Prime_Minister%2C_Shri_Narendra_Modi_visits_the_Serum_Institute_of_India%2C_in_Pune_on_November_28%2C_2020_%284%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Hydrating Vitamin C Serum — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0131",
        "url": "https://upload.wikimedia.org/wikipedia/commons/6/62/HBV_serum_markers-IT.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "Hydrating Vitamin C Serum — image 4",
        "sortOrder": 3
      },
      {
        "id": "img-0132",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/EN-before-after-Eyebrow-Enhancing-Serum.jpg/960px-EN-before-after-Eyebrow-Enhancing-Serum.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Hydrating Vitamin C Serum — image 5",
        "sortOrder": 4
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T16:44:40.289Z"
  },
  {
    "id": "prod-0133",
    "name": "Sulfate-Free Shampoo & Conditioner Set",
    "slug": "sulfate-free-shampoo-and-conditioner-set",
    "sku": "SKU-1020",
    "description": "Sulfate-Free Shampoo & Conditioner Set from PureRoot. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Beauty & Personal Care collection.",
    "shortDescription": "PureRoot · Beauty & Personal Care",
    "price": 21.5,
    "compareAtPrice": null,
    "stock": 36,
    "brand": "PureRoot",
    "isFeatured": true,
    "avgRating": 4.1,
    "reviewCount": 110,
    "categoryId": "cat-0126",
    "categorySlug": "beauty-and-personal-care",
    "categoryName": "Beauty & Personal Care",
    "images": [
      {
        "id": "img-0134",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Dove_shampoo_bottle.jpg/960px-Dove_shampoo_bottle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Sulfate-Free Shampoo & Conditioner Set — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0135",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/A_basic_of_shampoo.jpg/960px-A_basic_of_shampoo.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Sulfate-Free Shampoo & Conditioner Set — image 2",
        "sortOrder": 1
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T15:44:40.289Z"
  },
  {
    "id": "prod-0140",
    "name": "Matte Finish Lipstick Trio",
    "slug": "matte-finish-lipstick-trio",
    "sku": "SKU-1021",
    "description": "Matte Finish Lipstick Trio from Glowlab. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Beauty & Personal Care collection.",
    "shortDescription": "Glowlab · Beauty & Personal Care",
    "price": 18.99,
    "compareAtPrice": 23.99,
    "stock": 69,
    "brand": "Glowlab",
    "isFeatured": false,
    "avgRating": 3.8,
    "reviewCount": 107,
    "categoryId": "cat-0126",
    "categorySlug": "beauty-and-personal-care",
    "categoryName": "Beauty & Personal Care",
    "images": [
      {
        "id": "img-0141",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Lipstick_in_application_%286065375905%29.jpg/960px-Lipstick_in_application_%286065375905%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Matte Finish Lipstick Trio — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0142",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Lipstick_closing_down_-_geograph.org.uk_-_4888344.jpg/960px-Lipstick_closing_down_-_geograph.org.uk_-_4888344.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Matte Finish Lipstick Trio — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0143",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/Elite_lipstick.jpg/960px-Elite_lipstick.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Matte Finish Lipstick Trio — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0144",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/94/Namie_Amuro_making_of_Neonlight_Lipstick.jpg/960px-Namie_Amuro_making_of_Neonlight_Lipstick.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Matte Finish Lipstick Trio — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0136",
        "sku": "SKU-1021-V1",
        "name": "Matte Finish Lipstick Trio — Black",
        "attributes": {
          "color": "Black"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0137",
        "sku": "SKU-1021-V2",
        "name": "Matte Finish Lipstick Trio — White",
        "attributes": {
          "color": "White"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0138",
        "sku": "SKU-1021-V3",
        "name": "Matte Finish Lipstick Trio — Blue",
        "attributes": {
          "color": "Blue"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0139",
        "sku": "SKU-1021-V4",
        "name": "Matte Finish Lipstick Trio — Red",
        "attributes": {
          "color": "Red"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-13T14:44:40.289Z"
  },
  {
    "id": "prod-0145",
    "name": "Rechargeable Electric Trimmer",
    "slug": "rechargeable-electric-trimmer",
    "sku": "SKU-1022",
    "description": "Rechargeable Electric Trimmer from Groomtech. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Beauty & Personal Care collection.",
    "shortDescription": "Groomtech · Beauty & Personal Care",
    "price": 39,
    "compareAtPrice": null,
    "stock": 81,
    "brand": "Groomtech",
    "isFeatured": false,
    "avgRating": 3.8,
    "reviewCount": 73,
    "categoryId": "cat-0126",
    "categorySlug": "beauty-and-personal-care",
    "categoryName": "Beauty & Personal Care",
    "images": [
      {
        "id": "img-0146",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Huachang_Shaver_HC-6800_-_Beard_Trimmer-1794.jpg/960px-Huachang_Shaver_HC-6800_-_Beard_Trimmer-1794.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Rechargeable Electric Trimmer — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0147",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Huachang_Shaver_HC-6800_-_Beard_Trimmer-1795.jpg/960px-Huachang_Shaver_HC-6800_-_Beard_Trimmer-1795.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Rechargeable Electric Trimmer — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0148",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Huachang_Shaver_HC-6800_-_Beard_Trimmer-1796.jpg/960px-Huachang_Shaver_HC-6800_-_Beard_Trimmer-1796.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Rechargeable Electric Trimmer — image 3",
        "sortOrder": 2
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T13:44:40.289Z"
  },
  {
    "id": "prod-0154",
    "name": "Non-Slip Yoga Mat 6mm",
    "slug": "non-slip-yoga-mat-6mm",
    "sku": "SKU-1023",
    "description": "Non-Slip Yoga Mat 6mm from FlexFit. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Sports & Outdoors collection.",
    "shortDescription": "FlexFit · Sports & Outdoors",
    "price": 29.99,
    "compareAtPrice": 36.99,
    "stock": 35,
    "brand": "FlexFit",
    "isFeatured": true,
    "avgRating": 3.6,
    "reviewCount": 51,
    "categoryId": "cat-0149",
    "categorySlug": "sports-and-outdoors",
    "categoryName": "Sports & Outdoors",
    "images": [
      {
        "id": "img-0155",
        "url": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Oakley_yoga_mat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "Non-Slip Yoga Mat 6mm — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0156",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Yoga_mat.jpg/960px-Yoga_mat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Non-Slip Yoga Mat 6mm — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0157",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Closeup_of_the_woman_on_a_yoga_mat_stretching_her_hips._%2850398220748%29.jpg/960px-Closeup_of_the_woman_on_a_yoga_mat_stretching_her_hips._%2850398220748%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Non-Slip Yoga Mat 6mm — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0158",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Yogi_unrolling_yoga_mat_on_the_floor._%2850214718967%29.jpg/960px-Yogi_unrolling_yoga_mat_on_the_floor._%2850214718967%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Non-Slip Yoga Mat 6mm — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0150",
        "sku": "SKU-1023-V1",
        "name": "Non-Slip Yoga Mat 6mm — Black",
        "attributes": {
          "color": "Black"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0151",
        "sku": "SKU-1023-V2",
        "name": "Non-Slip Yoga Mat 6mm — White",
        "attributes": {
          "color": "White"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0152",
        "sku": "SKU-1023-V3",
        "name": "Non-Slip Yoga Mat 6mm — Blue",
        "attributes": {
          "color": "Blue"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0153",
        "sku": "SKU-1023-V4",
        "name": "Non-Slip Yoga Mat 6mm — Red",
        "attributes": {
          "color": "Red"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-13T12:44:40.289Z"
  },
  {
    "id": "prod-0159",
    "name": "Adjustable Dumbbell Set (5-25 lb)",
    "slug": "adjustable-dumbbell-set-5-25-lb",
    "sku": "SKU-1024",
    "description": "Adjustable Dumbbell Set (5-25 lb) from IronCore. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Sports & Outdoors collection.",
    "shortDescription": "IronCore · Sports & Outdoors",
    "price": 149,
    "compareAtPrice": null,
    "stock": 71,
    "brand": "IronCore",
    "isFeatured": true,
    "avgRating": 3.8,
    "reviewCount": 23,
    "categoryId": "cat-0149",
    "categorySlug": "sports-and-outdoors",
    "categoryName": "Sports & Outdoors",
    "images": [
      {
        "id": "img-0160",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Colorful_dumbbells_of_various_sizes.jpg/960px-Colorful_dumbbells_of_various_sizes.jpg",
        "altText": "Adjustable Dumbbell Set (5-25 lb) — image 1",
        "sortOrder": 0
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T11:44:40.289Z"
  },
  {
    "id": "prod-0161",
    "name": "2-Person Backpacking Tent",
    "slug": "2-person-backpacking-tent",
    "sku": "SKU-1025",
    "description": "2-Person Backpacking Tent from Trailhead. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Sports & Outdoors collection.",
    "shortDescription": "Trailhead · Sports & Outdoors",
    "price": 119,
    "compareAtPrice": 139,
    "stock": 79,
    "brand": "Trailhead",
    "isFeatured": false,
    "avgRating": 4.5,
    "reviewCount": 29,
    "categoryId": "cat-0149",
    "categorySlug": "sports-and-outdoors",
    "categoryName": "Sports & Outdoors",
    "images": [
      {
        "id": "img-0162",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/Camping_tent_trailer.JPG/960px-Camping_tent_trailer.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "2-Person Backpacking Tent — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0163",
        "url": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Large_Car_Camping_Tent.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
        "altText": "2-Person Backpacking Tent — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0164",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/Topboss_Plastic_Premium_Dome_Camping_Tent_IMG_3635.jpg/960px-Topboss_Plastic_Premium_Dome_Camping_Tent_IMG_3635.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "2-Person Backpacking Tent — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0165",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d9/White_and_yellow_camping_tent_in_the_middle_of_forest.jpg/960px-White_and_yellow_camping_tent_in_the_middle_of_forest.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "2-Person Backpacking Tent — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [],
    "createdAt": "2026-09-13T10:44:40.289Z"
  },
  {
    "id": "prod-0170",
    "name": "Insulated Stainless Water Bottle 32oz",
    "slug": "insulated-stainless-water-bottle-32oz",
    "sku": "SKU-1026",
    "description": "Insulated Stainless Water Bottle 32oz from FlexFit. Thoughtfully designed for everyday use, built to last, and backed by our standard quality guarantee. Part of the Sports & Outdoors collection.",
    "shortDescription": "FlexFit · Sports & Outdoors",
    "price": 24,
    "compareAtPrice": null,
    "stock": 73,
    "brand": "FlexFit",
    "isFeatured": false,
    "avgRating": 4.4,
    "reviewCount": 41,
    "categoryId": "cat-0149",
    "categorySlug": "sports-and-outdoors",
    "categoryName": "Sports & Outdoors",
    "images": [
      {
        "id": "img-0171",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Glass_Water_Bottle.JPG/960px-Glass_Water_Bottle.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Insulated Stainless Water Bottle 32oz — image 1",
        "sortOrder": 0
      },
      {
        "id": "img-0172",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Glass_water_bottle_positive_water_bottle_cheryl_myers_mypositivewater.com_my_positive_water_%2844%29.jpg/960px-Glass_water_bottle_positive_water_bottle_cheryl_myers_mypositivewater.com_my_positive_water_%2844%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Insulated Stainless Water Bottle 32oz — image 2",
        "sortOrder": 1
      },
      {
        "id": "img-0173",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Water_Bottle_Refill_-_Exmouth_Beach_-_2022.jpg/960px-Water_Bottle_Refill_-_Exmouth_Beach_-_2022.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Insulated Stainless Water Bottle 32oz — image 3",
        "sortOrder": 2
      },
      {
        "id": "img-0174",
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Zabarvan_water_bottle.jpg/960px-Zabarvan_water_bottle.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "altText": "Insulated Stainless Water Bottle 32oz — image 4",
        "sortOrder": 3
      }
    ],
    "variants": [
      {
        "id": "var-0166",
        "sku": "SKU-1026-V1",
        "name": "Insulated Stainless Water Bottle 32oz — Black",
        "attributes": {
          "color": "Black"
        },
        "priceDelta": 0,
        "stock": 10,
        "isActive": true
      },
      {
        "id": "var-0167",
        "sku": "SKU-1026-V2",
        "name": "Insulated Stainless Water Bottle 32oz — White",
        "attributes": {
          "color": "White"
        },
        "priceDelta": 0,
        "stock": 15,
        "isActive": true
      },
      {
        "id": "var-0168",
        "sku": "SKU-1026-V3",
        "name": "Insulated Stainless Water Bottle 32oz — Blue",
        "attributes": {
          "color": "Blue"
        },
        "priceDelta": 0,
        "stock": 20,
        "isActive": true
      },
      {
        "id": "var-0169",
        "sku": "SKU-1026-V4",
        "name": "Insulated Stainless Water Bottle 32oz — Red",
        "attributes": {
          "color": "Red"
        },
        "priceDelta": 0,
        "stock": 25,
        "isActive": true
      }
    ],
    "createdAt": "2026-09-13T09:44:40.289Z"
  }
];
